image: node:latest

stages:
  - build

build:
  stage: build
  tags:
    - hva
  script:
    - cd /builds/se-specialization-2023-1/projects-md/team-5.5/linkextractor/frontend
    - npm set progress=off
    - npm install
    - export NODE_ENV=production
    - npm run build
  cache:
    policy: push
    paths:
      - node_modules/
