image: node:latest
stages:
  - build

build:
  stage: build
  tags:
    - hva
  script:
    - npm set progress=off
    - npm install
    - export NODE_ENV=production
    - npm run build
  cache:
    policy: push
    paths:
      - node_modules/

